import type { Metadata } from 'next';
import { Geist, Geist_Mono, League_Gothic } from 'next/font/google';
import './globals.css';
import { NextIntlClientProvider } from 'next-intl';
import SmoothScroll from './components/SmoothScroll';
import { Navbar } from './components/Navbar';
import PageAnimatePresence from './components/PageAnimatePresence';
import { Footer } from './components/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const leagueGothic = League_Gothic({
  variable: '--font-league-gothic',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${leagueGothic.variable} antialiased overflow-hidden text-white selection:bg-white selection:text-black`}
      >
        <NextIntlClientProvider>
          <SmoothScroll>
            <Navbar />
            <PageAnimatePresence>{children}</PageAnimatePresence>
            <Footer />
          </SmoothScroll>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
